import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { FarcasterEmbed } from "react-farcaster-embed/dist/client";

const inter = Inter({ subsets: ["latin"] });

const castData = {
  hash: "0x234aa6ed38a3eb2ca3a7ef091d95c9ae2e48371c",
  threadHash: "0x234aa6ed38a3eb2ca3a7ef091d95c9ae2e48371c",
  author: {
    fid: 557,
    username: "pugson",
    displayName: "pugson",
    pfp: {
      url: "https://i.seadn.io/gae/5hjYfRyqiRJV4EQ7ieSJrmb1LtO_vcAvREXSqnlY4HXXBsvgh1vumOwj5e4GwGhppEU2jLC9qJHEgEkaJ9V_B02jIFY9XmzgK1_F?w=500&auto=format",
      verified: false,
    },
    profile: {
      bio: {
        text: "𝚆𝙾𝚁𝙺𝙸𝙽𝙶 𝙾𝙽: @vision 👁️ ✦  ensdata.net ✦ pugson.net/rfe ✦ 𝙿𝚄𝙶.𝙴𝚃𝙷 ✦ 𝙿𝚁𝙴𝚅: @rainbow 🌈 ",
        mentions: ["vision", "rainbow"],
        channelMentions: [],
      },
      location: {
        placeId: "",
        description: "",
      },
    },
    followerCount: 200380,
    followingCount: 1833,
    activeOnFcNetwork: true,
    viewerContext: {
      following: true,
    },
  },
  text: "i need this performance to last 4 hours https://youtu.be/sYHtQSPPaBU",
  timestamp: 1708589959000,
  mentions: [],
  attachments: {},
  embeds: {
    images: [],
    urls: [
      {
        type: "url",
        openGraph: {
          url: "https://warpcast.com/pugson/0xf5ec2883",
          sourceUrl: "https://warpcast.com/pugson/0xf5ec2883",
          title: "pugson on Warpcast",
          description: "one of those dabeull mornings",
          domain: "warpcast.com",
          image: "https://client.warpcast.com/v2/og-image?castHash=0xf5ec288354061c3de982f85899662fcd52a35b0b",
          useLargeImage: true,
        },
      },
      {
        type: "url",
        openGraph: {
          url: "https://youtu.be/sYHtQSPPaBU",
          sourceUrl: "https://youtu.be/sYHtQSPPaBU",
          title: "Dabeull - Messages From The Stars (Live in Paris)",
          domain: "youtube.com",
          image:
            "https://i.ytimg.com/vi/sYHtQSPPaBU/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGUgUChBMA8=&rs=AOn4CLCMGtzdUCRsGfBCkBmBrSDf9-F94Q",
          useLargeImage: true,
        },
      },
    ],
    videos: [],
    casts: [
      {
        hash: "0xf5ec288354061c3de982f85899662fcd52a35b0b",
        threadHash: "0xf5ec288354061c3de982f85899662fcd52a35b0b",
        parentSource: {
          type: "url",
          url: "chain://eip155:7777777/erc721:0xe96c21b136a477a6a97332694f0caae9fbb05634",
        },
        author: {
          fid: 557,
          username: "pugson",
          displayName: "pugson",
          pfp: {
            url: "https://i.seadn.io/gae/5hjYfRyqiRJV4EQ7ieSJrmb1LtO_vcAvREXSqnlY4HXXBsvgh1vumOwj5e4GwGhppEU2jLC9qJHEgEkaJ9V_B02jIFY9XmzgK1_F?w=500&auto=format",
            verified: false,
          },
          profile: {
            bio: {
              text: "𝚆𝙾𝚁𝙺𝙸𝙽𝙶 𝙾𝙽: @vision 👁️ ✦ ensdata.net ✦ abidata.net ✦ final-v3.zip ✦ 𝙿𝚄𝙶.𝙴𝚃𝙷  ",
              mentions: ["vision"],
              channelMentions: [],
            },
            location: {
              placeId: "",
              description: "",
            },
          },
          followerCount: 64430,
          followingCount: 1730,
          activeOnFcNetwork: true,
        },
        text: "one of those dabeull mornings",
        timestamp: 1708588807000,
        tags: [
          {
            type: "channel",
            id: "music",
            name: "Music",
            imageUrl:
              "https://ipfs.decentralized-content.com/ipfs/bafybeibdk7mvrhmud76ye6wm623sjgtiashik2imee7dkeliiq4wfissqq",
          },
        ],
      },
    ],
    unknowns: [],
    processedCastText: "i need this performance to last 4 hours",
  },
  ancestors: {
    count: 0,
    casts: [],
  },
  replies: {
    count: 2,
    casts: [],
  },
  reactions: {
    count: 17,
  },
  recasts: {
    count: 2,
  },
  watches: {
    count: 0,
  },
  tags: [],
  viewCount: 1200,
  quoteCount: 1,
  combinedRecastCount: 3,
  warpsTipped: 0,
  viewerContext: {
    reacted: false,
    recast: false,
    bookmarked: false,
  },
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 1fr 1fr",
            gap: "1rem",
          }}
        >
          <FarcasterEmbed castData={castData} />
          <FarcasterEmbed url="https://warpcast.com/kienfam/0x84016f26db8d35d647da718c5973458f9f49fe24" />
          <FarcasterEmbed url="https://warpcast.com/linda/0xa8fc16d13e235ab164dabc24d75e24ae62eacc05" />
          <FarcasterEmbed url="https://warpcast.com/pugson/0xce68f529" />
          <FarcasterEmbed url="https://warpcast.com/pugson/0x234aa6ed" />
          <FarcasterEmbed url="https://warpcast.com/builderszn/0xb488423d" />
          <FarcasterEmbed username="dwr" hash="0x48d47343" />
          <FarcasterEmbed url="https://warpcast.com/pugson/0xc672af1b" />
          <FarcasterEmbed url="https://warpcast.com/pugson/0x67dd4c5d" />
          <FarcasterEmbed url="https://warpcast.com/pugson/0x15f29fde" />
          <FarcasterEmbed url="https://warpcast.com/dwr.eth/0xd0a48a4a" />
          <FarcasterEmbed url="https://warpcast.com/pugson/0xf68b0f8a" />
          <FarcasterEmbed url="https://warpcast.com/builderszn/0x679f3e08" />
          <FarcasterEmbed url="https://warpcast.com/builderszn/0xb488423d" />
          <FarcasterEmbed url="https://warpcast.com/ted/0x04120d52" />
          <FarcasterEmbed url="https://warpcast.com/dwr.eth/0xd0a48a4a" />
          <FarcasterEmbed url="https://warpcast.com/pugson/0x4294c797" />
          <FarcasterEmbed url="https://warpcast.com/nonlinear.eth/0x40054241" />
          <FarcasterEmbed url="https://warpcast.com/pugson/0x774f6ddc" />
        </div>
      </main>
    </>
  );
}
