import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { FarcasterEmbed } from "react-farcaster-embed/dist/client";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 1fr 1fr",
            gap: "1rem",
          }}
        >
          <FarcasterEmbed url="https://warpcast.com/kienfam/0x84016f26db8d35d647da718c5973458f9f49fe24" />
          <FarcasterEmbed url="https://warpcast.com/linda/0xa8fc16d13e235ab164dabc24d75e24ae62eacc05" />
          <FarcasterEmbed url="https://warpcast.com/pugson/0xce68f529" />
          <FarcasterEmbed url="https://warpcast.com/pugson/0x234aa6ed" />
          <FarcasterEmbed url="https://warpcast.com/builderszn/0xb488423d" />
          <FarcasterEmbed username="dwr" hash="0x48d47343" />
          <FarcasterEmbed url="https://warpcast.com/pugson/0xc672af1b" />
          <FarcasterEmbed url="https://warpcast.com/pugson/0x67dd4c5d" />
          <FarcasterEmbed url="https://warpcast.com/pugson/0x15f29fde" />
          <FarcasterEmbed url="https://warpcast.com/dwr.eth/0xd0a48a4a" />
          <FarcasterEmbed url="https://warpcast.com/pugson/0xf68b0f8a" />
          <FarcasterEmbed url="https://warpcast.com/builderszn/0x679f3e08" />
          <FarcasterEmbed url="https://warpcast.com/builderszn/0xb488423d" />
          <FarcasterEmbed url="https://warpcast.com/ted/0x04120d52" />
          <FarcasterEmbed url="https://warpcast.com/dwr.eth/0xd0a48a4a" />
          <FarcasterEmbed url="https://warpcast.com/pugson/0x4294c797" />
          <FarcasterEmbed url="https://warpcast.com/nonlinear.eth/0x40054241" />
          <FarcasterEmbed url="https://warpcast.com/pugson/0x774f6ddc" />
        </div>
      </main>
    </>
  );
}
